# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-10 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('tag', tagging.fields.TagField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, default='media/images.jpeg', upload_to='')),
            ],
        ),
    ]
