# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-10 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_urldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='pictures')),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.Project')),
            ],
        ),
    ]
