# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-13 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_auto_20171011_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True)),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.Project')),
            ],
        ),
    ]
