# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-14 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='detail',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='tag',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
