# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-14 15:21
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_auto_20171014_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
