# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-14 15:23
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_textdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textdata',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
