# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-14 15:30
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_auto_20171014_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textdata',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='aa'),
        ),
    ]
