# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-15 05:12
from __future__ import unicode_literals

import Project.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0009_auto_20171014_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='folder',
            name='docfile',
            field=models.FileField(null=True, upload_to=Project.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
