# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-15 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0010_auto_20171015_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='docfile',
        ),
    ]
