# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-17 04:25
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0011_remove_folder_docfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='proj',
        ),
        migrations.AddField(
            model_name='picture',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.Folder'),
        ),
        migrations.AddField(
            model_name='picture',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='textdata',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.Folder'),
        ),
        migrations.AlterField(
            model_name='textdata',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
